name = "IntervalUnionArithmetic"
uuid = "bbd57523-681a-4e6b-a941-369dddcfdba8"
authors = ["Ander Gray <ander.gray@liverpool.ac.uk>"]
version = "0.1.0"

[deps]
IntervalArithmetic = "d1acc4aa-44c8-5952-acd4-ba5d80a2a253"
Reexport = "189a3867-3050-52da-a836-e630ba90ab69"
